services:
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: workzen-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - workzen-network

  migrate:
    depends_on:
      db:
        condition: service_healthy
    networks:
      - workzen-network

  app:
    container_name: workzen-be
    restart: always
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    networks:
      - workzen-network

  nginx:
    image: nginx:alpine
    container_name: workzen-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - workzen-network

volumes:
  pgdata:

networks:
  workzen-network:
    driver: bridge