services:
  db:
    ports:
      - "5433:5432"

  migrate:
    image: migrate/migrate
    volumes:
      - ./database/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/my_database?sslmode=disable",
      "up"
    ]

  app:
    build: .
    image: workzen-be-app-image:v1.0
    ports:
      - "8080:8080"
    env_file:
      - .env.dev