// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeCVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CvText        string                 `protobuf:"bytes,1,opt,name=cv_text,json=cvText,proto3" json:"cv_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeCVRequest) Reset() {
	*x = AnalyzeCVRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCVRequest) ProtoMessage() {}

func (x *AnalyzeCVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCVRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeCVRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeCVRequest) GetCvText() string {
	if x != nil {
		return x.CvText
	}
	return ""
}

type CVAnalysisResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Summary              string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Recommendation       string                 `protobuf:"bytes,2,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Skills               []string               `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	ExperienceHighlights []string               `protobuf:"bytes,4,rep,name=experience_highlights,json=experienceHighlights,proto3" json:"experience_highlights,omitempty"`
	FitScore             int32                  `protobuf:"varint,5,opt,name=fit_score,json=fitScore,proto3" json:"fit_score,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CVAnalysisResponse) Reset() {
	*x = CVAnalysisResponse{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CVAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CVAnalysisResponse) ProtoMessage() {}

func (x *CVAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CVAnalysisResponse.ProtoReflect.Descriptor instead.
func (*CVAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *CVAnalysisResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CVAnalysisResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *CVAnalysisResponse) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CVAnalysisResponse) GetExperienceHighlights() []string {
	if x != nil {
		return x.ExperienceHighlights
	}
	return nil
}

func (x *CVAnalysisResponse) GetFitScore() int32 {
	if x != nil {
		return x.FitScore
	}
	return 0
}

type MatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CvText        string                 `protobuf:"bytes,1,opt,name=cv_text,json=cvText,proto3" json:"cv_text,omitempty"`
	JdText        string                 `protobuf:"bytes,2,opt,name=jd_text,json=jdText,proto3" json:"jd_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchJobRequest) Reset() {
	*x = MatchJobRequest{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchJobRequest) ProtoMessage() {}

func (x *MatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchJobRequest.ProtoReflect.Descriptor instead.
func (*MatchJobRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *MatchJobRequest) GetCvText() string {
	if x != nil {
		return x.CvText
	}
	return ""
}

func (x *MatchJobRequest) GetJdText() string {
	if x != nil {
		return x.JdText
	}
	return ""
}

type JobMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	MatchedSkills []string               `protobuf:"bytes,2,rep,name=matched_skills,json=matchedSkills,proto3" json:"matched_skills,omitempty"`
	MissingSkills []string               `protobuf:"bytes,3,rep,name=missing_skills,json=missingSkills,proto3" json:"missing_skills,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Verdict       string                 `protobuf:"bytes,5,opt,name=verdict,proto3" json:"verdict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMatchResponse) Reset() {
	*x = JobMatchResponse{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMatchResponse) ProtoMessage() {}

func (x *JobMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMatchResponse.ProtoReflect.Descriptor instead.
func (*JobMatchResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *JobMatchResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *JobMatchResponse) GetMatchedSkills() []string {
	if x != nil {
		return x.MatchedSkills
	}
	return nil
}

func (x *JobMatchResponse) GetMissingSkills() []string {
	if x != nil {
		return x.MissingSkills
	}
	return nil
}

func (x *JobMatchResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *JobMatchResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"+\n" +
	"\x10AnalyzeCVRequest\x12\x17\n" +
	"\acv_text\x18\x01 \x01(\tR\x06cvText\"\xc0\x01\n" +
	"\x12CVAnalysisResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12&\n" +
	"\x0erecommendation\x18\x02 \x01(\tR\x0erecommendation\x12\x16\n" +
	"\x06skills\x18\x03 \x03(\tR\x06skills\x123\n" +
	"\x15experience_highlights\x18\x04 \x03(\tR\x14experienceHighlights\x12\x1b\n" +
	"\tfit_score\x18\x05 \x01(\x05R\bfitScore\"C\n" +
	"\x0fMatchJobRequest\x12\x17\n" +
	"\acv_text\x18\x01 \x01(\tR\x06cvText\x12\x17\n" +
	"\ajd_text\x18\x02 \x01(\tR\x06jdText\"\xb2\x01\n" +
	"\x10JobMatchResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12%\n" +
	"\x0ematched_skills\x18\x02 \x03(\tR\rmatchedSkills\x12%\n" +
	"\x0emissing_skills\x18\x03 \x03(\tR\rmissingSkills\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12\x18\n" +
	"\averdict\x18\x05 \x01(\tR\averdict2}\n" +
	"\tAIService\x129\n" +
	"\tAnalyzeCV\x12\x14.ai.AnalyzeCVRequest\x1a\x16.ai.CVAnalysisResponse\x125\n" +
	"\bMatchJob\x12\x13.ai.MatchJobRequest\x1a\x14.ai.JobMatchResponseB\x1dZ\x1bworkzen-be/internal/grpc/aib\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_proto_goTypes = []any{
	(*AnalyzeCVRequest)(nil),   // 0: ai.AnalyzeCVRequest
	(*CVAnalysisResponse)(nil), // 1: ai.CVAnalysisResponse
	(*MatchJobRequest)(nil),    // 2: ai.MatchJobRequest
	(*JobMatchResponse)(nil),   // 3: ai.JobMatchResponse
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.AIService.AnalyzeCV:input_type -> ai.AnalyzeCVRequest
	2, // 1: ai.AIService.MatchJob:input_type -> ai.MatchJobRequest
	1, // 2: ai.AIService.AnalyzeCV:output_type -> ai.CVAnalysisResponse
	3, // 3: ai.AIService.MatchJob:output_type -> ai.JobMatchResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
